<header>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#3b3b3b;">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#hikesnav" aria-controls="hikesnav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="hikesnav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 align-items-center">
                    <li class="nav-item">
                        <a class="nav-link" href="index.php"><img src="images/ARTTLogo.jpg" width="200px"></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link fs-2" href="about.php">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link fs-2" href="contact.php">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link fs-2" href="services.php">Services</a>
                    </li>
                </ul>
                <form class="d-flex" action="search.php" method="get">
                    <input class="form-control me-2" type="text" name="query" placeholder="Search" aria-label="Search" required>
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
</header>